### PR TITLE
Withdraw Nonce fix

### PR DESCRIPTION
**Pull request by lander86**
Withdraw Nonce fix

### CODE REVIEW

**Review by cronicc — DISMISSED** [review]

**Review by ysibirski — APPROVED** [review]
LGTM

**Review by otoumas — APPROVED** [review]
LGTM

**Comment by luisantoniocrag** [comment]
Hi I just tried the changes and I there is a extra `}` below the line

```js
const nonce_s = web3.utils.padLeft(nonce.toString(16), pad)
```

**Comment by luisantoniocrag** [comment]
Maybe you already saw it, but I left it because I got an error when trying the remix haha

**Review by otoumas — APPROVED** [review]
LGTM

**Pull request merged**
